// Accounts
export const FETCH_ACCOUNT_SUCCESS = "FETCH_ACCOUNT_SUCCESS";
export const MODIFY_INVITATION_SUCCESS = "MODIFY_INVITATION_SUCCESS";
export const SET_TOKEN_SUCCESS = "SET_TOKEN_SUCCESS";
export const CREATE_GROUP_SUCCESS = "CREATE_GROUP_SUCCESS";

// Restaurants
export const FETCH_RESTAURANTS_SUCCESS = "FETCH_RESTAURANTS_SUCCESS";
export const FETCH_RESTAURANTS_SEARCH_SUCCESS = "FETCH_RESTAURANTS_SEARCH_SUCCESS";
export const ADD_RESTAURANT_SUCCESS = "ADD_RESTAURANT_SUCCESS";
export const SET_ADD_RESTAURANT_FALSE = "SET_ADD_RESTAURANT_FALSE";

// Groups
export const FETCH_GROUP_SUCCESS = "FETCH_GROUP_SUCCESS";
export const REMOVE_ITEM_SUCCESS = "REMOVE_ITEM_SUCCESS";
export const ADD_ITEM_SUCCESS = "ADD_ITEM_SUCCESS";
export const ADD_FAVORITE_SUCCESS = "ADD_FAVORITE_SUCCESS";
export const DELETE_GROUP_SUCCESS = "DELETE_GROUP_SUCCESS";




// Geolocation
export const FETCH_NAVIGATION_SUCCESS = "FETCH_NAVIGATION_SUCCESS";

// Errors
export const ERROR_HANDLER = "ERROR_HANDLER";
export const CLEAR_ERROR = "CLEAR_ERROR";