import { StyleSheet } from "react-native";
import * as colors from "./colors";

export const containers = StyleSheet.create({
  standardLayout: {
    flex: 1,
    backgroundColor: colors.secondary,
    alignItems: "center",
    justifyContent: "center",
  },
  standardFlexStartLayout: {
    flex: 1,
    backgroundColor: colors.secondary,
    alignItems: "center",
    justifyContent: "flex-start",
  },
  spaceAround: {
    flex: 1,
    flexDirection: "column",
    backgroundColor: colors.secondary,
    justifyContent: "space-around",
    alignItems: "center",
    backgroundColor: "black",
  },
  spaceAroundShort: {
    width: "100%",
    flexBasis: "55%",
    flexDirection: "column",
    backgroundColor: colors.secondary,
    justifyContent: "space-around",
    alignItems: "center",
  },
  centered: {
    width: "100%",
    flexDirection: "column",
    backgroundColor: colors.secondary,
    justifyContent: "center",
    alignItems: "center",
  },
  spaceAroundRow: {
    flexDirection: "row",
    width: "100%",
    flexBasis: "20%",
    backgroundColor: colors.secondary,
    justifyContent: "space-around",
    alignItems: "center",
  },
  narrowBody: {
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
    width: "80%",
  },
  shortNarrowBody: {
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "space-around",
    flexBasis: "90%",
    width: "80%",
  },
  shortBody: {
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "space-around",
    flexBasis: "90%",
    width: "100%",
  },
  columnSpaceBetween: {
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "space-around",
    flexBasis: "40%",
  },
  centeredRow: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  addressContainer: {
    width: "100%",
    flexBasis: "40%",
    flexDirection: "column",
    justifyContent: "space-between",
    alignItems: "center",
  },
  addressSubContainer: {
    flex: 1,
    flexDirection: "column",
    justifyContent: "space-between",
    alignItems: "center",
  },
  itemListTile: {
    width: "100%",
    flex: 4,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  filterContainer: {
    width: "100%",
    height: 100,
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "flex-start",
    borderBottomWidth: 1,
    borderBottomColor: colors.white,
  },
  primaryFilterContainer: {
    width: "100%",
    height: 50,
    flexBasis: "10%",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    borderBottomWidth: 1,
    borderBottomColor: colors.white,
  },
  filterFieldContainer: {
    width: "100%",
    flexDirection: "row",
    height: 50,
    alignItems: "center",
    justifyContent: "flex-start",
  },
  filterFieldContainerScroll: {
    flexDirection: "row",
    height: 50,
    alignItems: "center",
    justifyContent: "flex-start",
    left: 0,
  },
  filterButtonContainer: {
    flexDirection: "column",
    borderBottomColor: colors.white,
    borderBottomWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
  },
  filterButtonContainerNoBorder: {
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
  },
  filterButtonContainerCuisine: {
    borderBottomColor: colors.white,
    borderBottomWidth: 1,
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    width: 100,
  },
  errorContainer: {
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    height: 50,
  },
});
